# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle


# SOURCES:
# https://www.mgsx.net/html5-libgdx-tutorial
# https://libgdx.com/wiki/deployment/deploying-your-application
# https://github.com/libgdx/libgdx/blob/0cd013f6efdc34404dcc7522ffe7c5ff48e35f1d/.github/workflows/test-pullrequest.yml
# https://github.com/ad-m/github-push-action

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'  
        cache: 'gradle'
    - name: Build Java & run task
      run: ./gradlew html:dist
      
    - name: Init new repo in dist folder and commit generated files
      run: |
        cd html/build/dist
        git init
        git add -A
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Add Changes"
      
    - name: Force push to destination branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force_with_lease: true
        directory: /home/runner/work/SonicSwirl/SonicSwirl/html/build/dist/
      
      
